import { useEffect, useMemo, useState } from 'react'
import { useFetch } from '../hooks/useFetch'
import { useT, type Locale } from '../i18n'
import type {
  AIDailyReport,
  AIDailyReportConfidence,
  AIDailyReportEvidenceStatus,
  AIDailyReportIndex,
  AIDailyReportPriority,
  DailyOperationVerdict,
  Severity,
} from '../types'
import { formatPower } from '../units'

interface Props {
  baseUrl: string
}

const COPY = {
  ko: {
    title: '운영 리포트',
    subtitle: '확정 실적과 내부 진단 JSON을 기반으로 전날 예측 운영을 해설합니다.',
    unavailable: '운영 리포트가 아직 생성되지 않았습니다. 다음 ETL 이후 자동 생성됩니다.',
    provider: '생성 방식',
    fallback: '규칙 기반 fallback',
    openai: 'OpenAI',
    fallbackBadge: '시스템 자동 진단',
    openaiBadge: 'AI 심층 운영 해설',
    englishFallbackBadge: '영어 원문 표시',
    fallbackNotice: 'OpenAI 호출 없이 deterministic JSON만으로 생성된 자동 진단입니다.',
    englishFallbackNotice: '번역 생성에 실패하여 영어 마스터 리포트를 표시합니다.',
    reportDate: '리포트 날짜',
    language: '리포트 언어',
    generatedAt: '생성 시각',
    performance: '정량 요약',
    modelMae: '모델 MAE',
    tepcoMae: 'TEPCO MAE',
    modelWape: '모델 WAPE',
    tepcoWape: 'TEPCO WAPE',
    verdict: '운영 판단',
    hypotheses: '원인 가설',
    recommendations: '개선 후보',
    evidence: '근거',
    limitations: '한계',
    notes: '운영 메모',
    inputVersion: '입력 버전',
    inputFingerprint: '입력 지문',
    sourceGeneratedAt: '입력 생성 시각',
    operationReport: '운영 리포트 입력',
    diagnostics: '운영 진단',
    coverage: '커버리지',
    finalCoverage: '확정 실측',
    calibrationCoverage: '보정 스냅샷',
    controller: '보정 컨트롤러',
    stageAttribution: '단계별 영향',
    bandQuality: '예측밴드 품질',
    rollingPattern: '최근 반복 패턴',
    freezeImpact: '보존 예측선 영향',
    capHit: 'Cap 도달',
    latestResidual: '최근 잔차',
    actualSlope: '실측 기울기',
    modelSlope: '모델 기울기',
    p95Coverage: 'p95 커버',
    p99Coverage: 'p99 커버',
    medianBandWidth: '중앙 밴드폭',
    repeatedMiss: '반복 오차',
    noDiagnostics: '표시할 추가 진단 정보가 없습니다.',
    replayCommand: '검증 명령',
    commandStatus: '명령 상태',
    implementedCommand: '구현됨',
    proposedCommand: '제안형',
    manualValidation: '수동 검증',
    noHypotheses: '표시할 원인 가설이 없습니다.',
    noRecommendations: '표시할 개선 후보가 없습니다.',
    confirmed: '직접 근거',
    partial: '정황 근거',
    notObserved: '확인 불가',
    severityInfo: '참고',
    severityWarning: '검토 필요',
    severityCritical: '우선 점검',
    confidenceLow: '신뢰도 낮음',
    confidenceMedium: '신뢰도 보통',
    confidenceHigh: '신뢰도 높음',
    priorityLow: '낮음',
    priorityMedium: '보통',
    priorityHigh: '높음',
    modelBetter: '모델 우세',
    tepcoBetter: 'TEPCO 우세',
    close: '비슷함',
    mixed: '혼재',
    insufficient: '부족',
  },
  en: {
    title: 'Ops Report',
    subtitle: 'Narrative review of previous-day forecast operations from confirmed actuals and internal diagnostics.',
    unavailable: 'Ops report is not available yet. It will be generated by the next ETL run.',
    provider: 'Generator',
    fallback: 'Rule-based fallback',
    openai: 'OpenAI',
    fallbackBadge: 'System Auto Diagnosis',
    openaiBadge: 'AI Deep Ops Analysis',
    englishFallbackBadge: 'English Source Shown',
    fallbackNotice: 'This automatic diagnosis was generated from deterministic JSON without an OpenAI call.',
    englishFallbackNotice: 'Localization failed, so the English master report is shown.',
    reportDate: 'Report date',
    language: 'Report language',
    generatedAt: 'Generated',
    performance: 'Metrics',
    modelMae: 'Model MAE',
    tepcoMae: 'TEPCO MAE',
    modelWape: 'Model WAPE',
    tepcoWape: 'TEPCO WAPE',
    verdict: 'Assessment',
    hypotheses: 'Root-cause hypotheses',
    recommendations: 'Improvement candidates',
    evidence: 'Evidence',
    limitations: 'Limitations',
    notes: 'Operator notes',
    inputVersion: 'Input Version',
    inputFingerprint: 'Input fingerprint',
    sourceGeneratedAt: 'Input generated',
    operationReport: 'Operation report input',
    diagnostics: 'Ops diagnostics',
    coverage: 'Coverage',
    finalCoverage: 'Final actuals',
    calibrationCoverage: 'Calibration snapshot',
    controller: 'Controller',
    stageAttribution: 'Stage attribution',
    bandQuality: 'Band quality',
    rollingPattern: 'Rolling pattern',
    freezeImpact: 'Published forecast freeze',
    capHit: 'Cap hit',
    latestResidual: 'Latest residual',
    actualSlope: 'Actual slope',
    modelSlope: 'Model slope',
    p95Coverage: 'p95 coverage',
    p99Coverage: 'p99 coverage',
    medianBandWidth: 'Median band width',
    repeatedMiss: 'Repeated miss',
    noDiagnostics: 'No additional diagnostics to display.',
    replayCommand: 'Replay command',
    commandStatus: 'Command status',
    implementedCommand: 'Implemented',
    proposedCommand: 'Proposed',
    manualValidation: 'Manual validation',
    noHypotheses: 'No hypotheses to display.',
    noRecommendations: 'No recommendations to display.',
    confirmed: 'Direct evidence',
    partial: 'Circumstantial',
    notObserved: 'Not observed',
    severityInfo: 'Info',
    severityWarning: 'Needs Review',
    severityCritical: 'Priority Review',
    confidenceLow: 'Low confidence',
    confidenceMedium: 'Medium confidence',
    confidenceHigh: 'High confidence',
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
    modelBetter: 'Model better',
    tepcoBetter: 'TEPCO better',
    close: 'Close',
    mixed: 'Mixed',
    insufficient: 'Insufficient',
  },
  ja: {
    title: '運用レポート',
    subtitle: '確定実績と内部診断JSONをもとに前日の予測運用を解説します。',
    unavailable: '運用レポートはまだ生成されていません。次回ETL後に自動生成されます。',
    provider: '生成方式',
    fallback: 'ルールベースfallback',
    openai: 'OpenAI',
    fallbackBadge: 'システム自動診断',
    openaiBadge: 'AI詳細運用解説',
    englishFallbackBadge: '英語原文表示',
    fallbackNotice: 'OpenAI呼び出しなしでdeterministic JSONから生成した自動診断です。',
    englishFallbackNotice: '翻訳生成に失敗したため、英語マスターレポートを表示しています。',
    reportDate: 'レポート日付',
    language: 'レポート言語',
    generatedAt: '生成時刻',
    performance: '定量サマリー',
    modelMae: 'モデル MAE',
    tepcoMae: 'TEPCO MAE',
    modelWape: 'モデル WAPE',
    tepcoWape: 'TEPCO WAPE',
    verdict: '運用判断',
    hypotheses: '原因仮説',
    recommendations: '改善候補',
    evidence: '根拠',
    limitations: '制約',
    notes: '運用メモ',
    inputVersion: '入力バージョン',
    inputFingerprint: '入力フィンガープリント',
    sourceGeneratedAt: '入力生成時刻',
    operationReport: '運用レポート入力',
    diagnostics: '運用診断',
    coverage: 'カバレッジ',
    finalCoverage: '確定実測',
    calibrationCoverage: '補正スナップショット',
    controller: '補正コントローラー',
    stageAttribution: '段階別影響',
    bandQuality: '予測バンド品質',
    rollingPattern: '直近の反復パターン',
    freezeImpact: '公開予測線の保持影響',
    capHit: 'Cap到達',
    latestResidual: '直近残差',
    actualSlope: '実測傾き',
    modelSlope: 'モデル傾き',
    p95Coverage: 'p95カバー',
    p99Coverage: 'p99カバー',
    medianBandWidth: '中央値バンド幅',
    repeatedMiss: '反復誤差',
    noDiagnostics: '表示する追加診断情報はありません。',
    replayCommand: '検証コマンド',
    commandStatus: 'コマンド状態',
    implementedCommand: '実装済み',
    proposedCommand: '提案',
    manualValidation: '手動検証',
    noHypotheses: '表示する原因仮説はありません。',
    noRecommendations: '表示する改善候補はありません。',
    confirmed: '直接根拠',
    partial: '状況証拠',
    notObserved: '確認不可',
    severityInfo: '情報',
    severityWarning: '要確認',
    severityCritical: '優先確認',
    confidenceLow: '信頼度 低',
    confidenceMedium: '信頼度 中',
    confidenceHigh: '信頼度 高',
    priorityLow: '低',
    priorityMedium: '中',
    priorityHigh: '高',
    modelBetter: 'モデル優勢',
    tepcoBetter: 'TEPCO優勢',
    close: '同等',
    mixed: '混在',
    insufficient: '不足',
  },
}

function fmtDateTime(value: string | null | undefined, locale: Locale): string {
  if (!value) return '-'
  return new Date(value).toLocaleString(locale === 'ko' ? 'ko-KR' : locale === 'ja' ? 'ja-JP' : 'en-US', {
    timeZone: 'Asia/Tokyo',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

function fmtPct(value: number | null | undefined): string {
  if (value == null) return '-'
  return `${value.toFixed(2)}%`
}

function fmtRatioPct(value: number | null | undefined): string {
  if (value == null) return '-'
  return `${(value * 100).toFixed(1)}%`
}

function fmtPowerMaybe(value: number | null | undefined, locale: Locale): string {
  if (value == null) return '-'
  return formatPower(value, locale)
}

function fmtSignedPower(value: number | null | undefined, locale: Locale): string {
  if (value == null) return '-'
  const sign = value > 0 ? '+' : ''
  return `${sign}${formatPower(value, locale)}`
}

function fmtHour(hour: number | null | undefined): string {
  if (hour == null) return '-'
  return `${String(hour).padStart(2, '0')}:00`
}

function fmtHourList(hours: number[] | null | undefined): string {
  if (!hours?.length) return '-'
  return hours.slice(0, 6).map(fmtHour).join(', ')
}

function fmtBool(value: boolean | null | undefined, locale: Locale): string {
  if (value == null) return '-'
  if (locale === 'ja') return value ? 'はい' : 'いいえ'
  if (locale === 'en') return value ? 'Yes' : 'No'
  return value ? '예' : '아니오'
}

function commandStatusLabel(
  status: string | null | undefined,
  labels: typeof COPY.ko,
): string {
  if (status === 'implemented') return labels.implementedCommand
  if (status === 'manual_validation') return labels.manualValidation
  if (status === 'proposed_not_implemented') return labels.proposedCommand
  return '-'
}

function shortFingerprint(value: string | null | undefined): string {
  if (!value) return '-'
  return value.replace(/^sha256:/, '').slice(0, 12)
}

function isFallbackNoteForOpenAI(note: string): boolean {
  const lower = note.toLowerCase()
  return (
    lower.includes('fallback')
    || note.includes('OpenAI 호출 없이')
    || lower.includes('without calling openai')
    || note.includes('OpenAIを呼び出さず')
  )
}

function verdictLabel(verdict: DailyOperationVerdict | undefined, labels: typeof COPY.ko): string {
  if (verdict === 'model_better') return labels.modelBetter
  if (verdict === 'tepco_better') return labels.tepcoBetter
  if (verdict === 'close') return labels.close
  if (verdict === 'mixed') return labels.mixed
  return labels.insufficient
}

function severityLabel(severity: Severity, labels: typeof COPY.ko): string {
  if (severity === 'critical') return labels.severityCritical
  if (severity === 'warning') return labels.severityWarning
  return labels.severityInfo
}

function confidenceLabel(confidence: AIDailyReportConfidence, labels: typeof COPY.ko): string {
  if (confidence === 'high') return labels.confidenceHigh
  if (confidence === 'low') return labels.confidenceLow
  return labels.confidenceMedium
}

function priorityLabel(priority: AIDailyReportPriority, labels: typeof COPY.ko): string {
  if (priority === 'high') return labels.priorityHigh
  if (priority === 'low') return labels.priorityLow
  return labels.priorityMedium
}

function evidenceStatusLabel(status: AIDailyReportEvidenceStatus, labels: typeof COPY.ko): string {
  if (status === 'confirmed') return labels.confirmed
  if (status === 'not_observed') return labels.notObserved
  return labels.partial
}

function evidenceStatusBadge(status: AIDailyReportEvidenceStatus): string {
  if (status === 'confirmed') return 'ok'
  if (status === 'not_observed') return 'info'
  return 'warning'
}

function evidenceStatusClass(status: AIDailyReportEvidenceStatus): string {
  if (status === 'confirmed') return 'confirmed'
  if (status === 'not_observed') return 'not-observed'
  return 'partial'
}

function providerBadgeClass(provider: AIDailyReport['generator']['provider']): string {
  return provider === 'openai' ? 'openai' : 'fallback'
}

function languageDisplayName(language: AIDailyReport['language'] | AIDailyReport['contentLanguage'] | undefined): string {
  if (language === 'ko') return '한국어'
  if (language === 'ja') return '日本語'
  if (language === 'en') return 'English'
  return '-'
}

function limitationText(item: string, locale: Locale): string {
  const lower = item.toLowerCase()
  const mentionsRawSeries = (
    lower.includes('raw 24-hour')
    || lower.includes('raw time-series')
    || lower.includes('raw time series')
    || lower.includes('time-series data')
    || lower.includes('time series data')
    || item.includes('원시 시간')
    || item.includes('원본 행')
    || item.includes('時系列')
  )
  if (!mentionsRawSeries) return item
  if (locale === 'ja') {
    return 'このレポートは、要約指標、主要な誤差時間帯、内部補正ログを基準に作成されています。'
  }
  if (locale === 'en') {
    return 'This report is based on summary metrics, key miss windows, and internal calibration logs.'
  }
  return '이 리포트는 요약 지표, 주요 오차 구간, 내부 보정 로그를 기준으로 작성되었습니다.'
}

function StatCard({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="validation-stat">
      <div className="validation-stat-label">{label}</div>
      <div className="validation-stat-value">{value}</div>
      {sub && <div className="validation-stat-sub">{sub}</div>}
    </div>
  )
}

function EvidenceList({ report, index }: { report: AIDailyReport; index: number }) {
  const { locale } = useT()
  const labels = COPY[locale]
  const hypothesis = report.rootCauseHypotheses[index]
  if (!hypothesis?.evidence.length) return null

  return (
    <div className="ops-evidence">
      <div className="ops-section-kicker">{labels.evidence}</div>
      {hypothesis.evidence.slice(0, 3).map((item, evidenceIndex) => (
        <span key={`${item.source}-${item.metric}-${evidenceIndex}`} className="alert-metric-chip">
          <strong>{item.metric}</strong>
          {String(item.value ?? '-')}
          {item.unit ? ` ${item.unit}` : ''}
          {item.hour != null ? ` @ ${String(item.hour).padStart(2, '0')}:00` : ''}
        </span>
      ))}
    </div>
  )
}

function DiagnosticPanel({ report }: { report: AIDailyReport }) {
  const { locale } = useT()
  const labels = COPY[locale]
  const context = report.diagnosticContext
  if (!context) {
    return (
      <div className="card">
        <div className="card-title">{labels.diagnostics}</div>
        <div className="empty-msg">{labels.noDiagnostics}</div>
      </div>
    )
  }

  const finalCoverage = context.coverageContext?.finalActualCoverage
  const calibrationCoverage = context.coverageContext?.intradayCalibrationCoverage
  const controller = context.controllerDiagnosis
  const bandQuality = context.bandQuality
  const rollingPattern = context.rollingPatternContext
  const stageRows = context.stageAttribution?.largestStageShifts ?? []
  const freezeGaps = context.freezeImpact?.largestGaps ?? []
  const repeatedMisses = rollingPattern?.sameBandRepeatedMisses ?? []

  return (
    <div className="card ops-diagnostics">
      <div className="card-title">{labels.diagnostics}</div>

      <div className="ops-diagnostic-grid">
        <section className="ops-mini-section">
          <div className="ops-section-kicker">{labels.coverage}</div>
          <div className="ops-kv-grid">
            <span>{labels.finalCoverage}</span>
            <strong>
              {finalCoverage?.observedHours ?? '-'} / {finalCoverage?.comparableHours ?? '-'}
            </strong>
            <span>{labels.calibrationCoverage}</span>
            <strong>
              {calibrationCoverage?.observedHours ?? '-'} / 24
            </strong>
            <span>fallback</span>
            <strong>{finalCoverage?.fallbackActualHours ?? '-'}</strong>
            <span>last observed</span>
            <strong>{fmtHour(calibrationCoverage?.lastObservedHour)}</strong>
          </div>
        </section>

        <section className="ops-mini-section">
          <div className="ops-section-kicker">{labels.controller}</div>
          <div className="ops-kv-grid">
            <span>baseAdjustment</span>
            <strong>{fmtSignedPower(controller?.baseAdjustmentMw, locale)}</strong>
            <span>{labels.capHit}</span>
            <strong>{fmtBool(controller?.capHitLikely, locale)}</strong>
            <span>{labels.latestResidual}</span>
            <strong>{fmtSignedPower(controller?.residualTrend?.latestResidualMw, locale)}</strong>
            <span>{labels.actualSlope}</span>
            <strong>{fmtSignedPower(controller?.slopeContext?.latestActualSlopeMw, locale)}</strong>
            <span>{labels.modelSlope}</span>
            <strong>{fmtSignedPower(controller?.slopeContext?.latestModelSlopeMw, locale)}</strong>
          </div>
          {!!controller?.flags?.length && (
            <div className="ops-chip-row">
              {controller.flags.slice(0, 6).map(flag => (
                <span key={flag} className="alert-metric-chip">{flag}</span>
              ))}
            </div>
          )}
        </section>

        <section className="ops-mini-section">
          <div className="ops-section-kicker">{labels.bandQuality}</div>
          <div className="ops-kv-grid">
            <span>{labels.p95Coverage}</span>
            <strong>
              {bandQuality?.p95CoverageHours ?? '-'} / {bandQuality?.comparableHours ?? '-'}
              {' '}
              ({fmtRatioPct(bandQuality?.p95CoverageRate)})
            </strong>
            <span>{labels.p99Coverage}</span>
            <strong>
              {bandQuality?.p99CoverageHours ?? '-'} / {bandQuality?.comparableHours ?? '-'}
              {' '}
              ({fmtRatioPct(bandQuality?.p99CoverageRate)})
            </strong>
            <span>{labels.medianBandWidth} p95</span>
            <strong>{fmtPowerMaybe(bandQuality?.medianP95HalfWidthMw, locale)}</strong>
            <span>outside p95</span>
            <strong>{fmtHourList(bandQuality?.outsideP95Hours)}</strong>
          </div>
        </section>

        <section className="ops-mini-section">
          <div className="ops-section-kicker">{labels.rollingPattern}</div>
          <div className="ops-kv-grid">
            <span>lookback</span>
            <strong>{rollingPattern?.lookbackDays ?? '-'}</strong>
            <span>verdict</span>
            <strong>{rollingPattern?.recentTrendVerdict ?? '-'}</strong>
          </div>
          {repeatedMisses.length > 0 ? (
            <div className="ops-chip-row">
              {repeatedMisses.slice(0, 3).map(item => (
                <span key={`${item.band}-${item.dominantDirection}`} className="alert-metric-chip">
                  <strong>{item.label ?? item.band}</strong>
                  {item.dominantDirection ?? '-'} / {item.sameDirectionMissDays ?? 0}d
                </span>
              ))}
            </div>
          ) : (
            <p className="ops-muted">{labels.noDiagnostics}</p>
          )}
        </section>
      </div>

      {(stageRows.length > 0 || freezeGaps.length > 0) && (
        <div className="ops-diagnostic-detail">
          {stageRows.length > 0 && (
            <section>
              <div className="ops-section-kicker">{labels.stageAttribution}</div>
              <div className="ops-stage-list">
                {stageRows.slice(0, 3).map(row => (
                  <div key={`${row.hour}-${row.netStageShiftMw}`} className="ops-stage-row">
                    <div className="ops-stage-hour">{fmtHour(row.hour)}</div>
                    <div className="ops-stage-steps">
                      {row.stageImpactSummary.slice(0, 7).map(stage => (
                        <span key={`${row.hour}-${stage.stage}`} className="ops-stage-step">
                          <span>{stage.stage}</span>
                          <strong>{fmtPowerMaybe(stage.value_mw, locale)}</strong>
                          {stage.delta_from && (
                            <em>{fmtSignedPower(stage.delta_mw, locale)}</em>
                          )}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )}

          {freezeGaps.length > 0 && (
            <section>
              <div className="ops-section-kicker">{labels.freezeImpact}</div>
              <div className="ops-chip-row">
                {freezeGaps.slice(0, 4).map(gap => (
                  <span key={gap.hour} className="alert-metric-chip">
                    <strong>{fmtHour(gap.hour)}</strong>
                    {fmtSignedPower(gap.freezeGapMw, locale)}
                  </span>
                ))}
              </div>
            </section>
          )}
        </div>
      )}
    </div>
  )
}

export function OpsReportPanel({ baseUrl }: Props) {
  const { t, locale, fmtDate } = useT()
  const labels = COPY[locale]
  const reportBase = `${baseUrl}reports/ai/daily/${locale}/`
  const index = useFetch<AIDailyReportIndex>(`${reportBase}index.json`)
  const reports = index.data?.reports ?? []
  const reportDatesKey = useMemo(
    () => reports.map(item => item.date).join('|'),
    [reports],
  )
  const latestDate = index.data?.latest?.date ?? null
  const [selectedDate, setSelectedDate] = useState<string | null>(null)
  const reportDate = selectedDate ?? latestDate
  const report = useFetch<AIDailyReport>(reportDate ? `${reportBase}${reportDate}.json` : null)
  const loading = index.loading || report.loading
  const selectedReport = report.data
  const usesEnglishFallback = selectedReport?.contentLanguage === 'en' && selectedReport.language !== 'en'
  const visibleOperatorNotes = selectedReport?.operatorNotes.filter(note => (
    selectedReport.generator.provider !== 'openai' || !isFallbackNoteForOpenAI(note)
  )) ?? []

  useEffect(() => {
    if (!latestDate) return
    const hasSelectedDate = reports.some(item => item.date === selectedDate)
    if (!selectedDate || !hasSelectedDate) {
      setSelectedDate(latestDate)
    }
  }, [latestDate, selectedDate, reportDatesKey, reports])

  return (
    <div className="tab-content">
      <div className="date-header">
        <h2>{labels.title}</h2>
        <p>{labels.subtitle}</p>
      </div>

      {reports.length > 0 && (
        <div className="card ops-report-controls">
          <label htmlFor="ops-report-date">{labels.reportDate}</label>
          <select
            id="ops-report-date"
            value={reportDate ?? ''}
            onChange={event => setSelectedDate(event.target.value)}
          >
            {[...reports].reverse().map(item => (
              <option key={item.date} value={item.date}>
                {fmtDate(item.date)}
              </option>
            ))}
          </select>
        </div>
      )}

      {loading && <div className="loading">{t.loading}</div>}

      {!loading && !selectedReport && (
        <div className="card empty-msg">{labels.unavailable}</div>
      )}

      {!loading && selectedReport && (
        <>
          <div className="card ops-report-summary">
            <div className="ops-report-heading">
              <div>
                <div className="card-title">{fmtDate(selectedReport.date)}</div>
                <h3>{selectedReport.executiveSummary.headline}</h3>
              </div>
              <div className="ops-report-badges">
                <span className={`badge ops-provider-badge ${providerBadgeClass(selectedReport.generator.provider)}`}>
                  {selectedReport.generator.provider === 'openai' ? labels.openaiBadge : labels.fallbackBadge}
                </span>
                {usesEnglishFallback && (
                  <span className="badge info">{labels.englishFallbackBadge}</span>
                )}
                <span className={`badge ${selectedReport.executiveSummary.severity}`}>
                  {severityLabel(selectedReport.executiveSummary.severity, labels)}
                </span>
              </div>
            </div>
            <p className="ops-report-text">{selectedReport.executiveSummary.summary}</p>
            {selectedReport.generator.provider === 'fallback' && (
              <div className="ops-provider-note">{labels.fallbackNotice}</div>
            )}
            {usesEnglishFallback && (
              <div className="ops-provider-note">{labels.englishFallbackNotice}</div>
            )}
            <div className="validation-stat-grid compact">
              <StatCard
                label={labels.provider}
                value={selectedReport.generator.provider === 'fallback' ? labels.fallback : labels.openai}
                sub={selectedReport.generator.model ?? undefined}
              />
              <StatCard
                label={labels.language}
                value={languageDisplayName(selectedReport.contentLanguage ?? selectedReport.language)}
                sub={usesEnglishFallback ? languageDisplayName(selectedReport.language) : undefined}
              />
              <StatCard label={labels.generatedAt} value={fmtDateTime(selectedReport.generatedAt, locale)} />
              <StatCard
                label={labels.verdict}
                value={verdictLabel(selectedReport.executiveSummary.modelVerdict, labels)}
                sub={confidenceLabel(selectedReport.executiveSummary.confidence, labels)}
              />
            </div>
          </div>

          <div className="card">
            <div className="card-title">{labels.performance}</div>
            <div className="validation-stat-grid compact">
              <StatCard label={labels.modelMae} value={fmtPowerMaybe(selectedReport.performance.modelMaeMw, locale)} />
              <StatCard label={labels.tepcoMae} value={fmtPowerMaybe(selectedReport.performance.tepcoMaeMw, locale)} />
              <StatCard label={labels.modelWape} value={fmtPct(selectedReport.performance.modelWapePct)} />
              <StatCard label={labels.tepcoWape} value={fmtPct(selectedReport.performance.tepcoWapePct)} />
            </div>
          </div>

          <DiagnosticPanel report={selectedReport} />

          {selectedReport.inputSnapshot && (
            <div className="card">
              <div className="card-title">{labels.inputVersion}</div>
              <div className="validation-stat-grid compact">
                <StatCard
                  label={labels.inputFingerprint}
                  value={shortFingerprint(selectedReport.inputSnapshot.fingerprint)}
                />
                <StatCard
                  label={labels.sourceGeneratedAt}
                  value={fmtDateTime(selectedReport.inputSnapshot.createdAt, locale)}
                />
                <StatCard
                  label={labels.operationReport}
                  value={selectedReport.inputSnapshot.sources.operationReport?.date ?? '-'}
                  sub={fmtDateTime(selectedReport.inputSnapshot.sources.operationReport?.generatedAt, locale)}
                />
              </div>
            </div>
          )}

          <div className="card">
            <div className="card-title">{labels.hypotheses}</div>
            {selectedReport.rootCauseHypotheses.length === 0 ? (
              <div className="empty-msg">{labels.noHypotheses}</div>
            ) : (
              <div className="ops-list">
                {selectedReport.rootCauseHypotheses.map((hypothesis, hypothesisIndex) => (
                  <div
                    key={hypothesis.id}
                    className={`ops-list-item evidence-${evidenceStatusClass(hypothesis.evidenceStatus)}`}
                  >
                    <div className="ops-list-head">
                      <strong>{hypothesis.title}</strong>
                      <span className={`badge ${evidenceStatusBadge(hypothesis.evidenceStatus)} ops-evidence-badge ${evidenceStatusClass(hypothesis.evidenceStatus)}`}>
                        {evidenceStatusLabel(hypothesis.evidenceStatus, labels)}
                      </span>
                    </div>
                    <p>{hypothesis.explanation}</p>
                    {hypothesis.relatedFeatures.length > 0 && (
                      <div className="ops-chip-row">
                        {hypothesis.relatedFeatures.slice(0, 5).map(feature => (
                          <span key={feature} className="alert-metric-chip">{feature}</span>
                        ))}
                      </div>
                    )}
                    <EvidenceList report={selectedReport} index={hypothesisIndex} />
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="card">
            <div className="card-title">{labels.recommendations}</div>
            {selectedReport.featureRecommendations.length === 0 ? (
              <div className="empty-msg">{labels.noRecommendations}</div>
            ) : (
              <div className="ops-list">
                {selectedReport.featureRecommendations.map(item => (
                  <div key={item.id} className="ops-list-item">
                    <div className="ops-list-head">
                      <strong>{item.target}</strong>
                      <span className="badge info">{priorityLabel(item.priority, labels)}</span>
                    </div>
                    <p>{item.suggestion}</p>
                    <p>{item.expectedEffect}</p>
                    <p className="ops-muted">{item.risk}</p>
                    <p className="ops-muted">{item.validationPlan}</p>
                    {(item.proposedReplayCommand || item.commandStatus) && (
                      <div className="ops-command">
                        <span>{labels.commandStatus}: {commandStatusLabel(item.commandStatus, labels)}</span>
                        {item.proposedReplayCommand && (
                          <code>{item.proposedReplayCommand}</code>
                        )}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {(visibleOperatorNotes.length > 0 || selectedReport.limitations.length > 0) && (
            <div className="card">
              {visibleOperatorNotes.length > 0 && (
                <>
                  <div className="card-title">{labels.notes}</div>
                  <ul className="ops-bullet-list">
                    {visibleOperatorNotes.map(note => <li key={note}>{note}</li>)}
                  </ul>
                </>
              )}
              {selectedReport.limitations.length > 0 && (
                <>
                  <div className="card-title ops-limits-title">{labels.limitations}</div>
                  <ul className="ops-bullet-list">
                    {selectedReport.limitations.map(item => (
                      <li key={item}>{limitationText(item, locale)}</li>
                    ))}
                  </ul>
                </>
              )}
            </div>
          )}
        </>
      )}
    </div>
  )
}
