import { useState } from 'react'
import {
  Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from 'recharts'
import { useFetch } from '../hooks/useFetch'
import { useT, type Locale } from '../i18n'
import type {
  BacktestMetrics,
  DailyOperationReport,
  DailyOperationReportIndex,
  ForecastAccuracyDaily,
  ForecastAccuracyJSON,
  ModelBacktestJSON,
} from '../types'
import { powerDisplayValue, powerUnit } from '../units'
import { VintageComparison } from './VintageComparison'
import {
  errorGap, formatErrorPct, formatErrorPower, formatExactMw, isPartialDay, referenceDays, referenceMetricValue,
  type ErrorMetric,
} from '../validationMetrics'

interface Props {
  baseUrl: string
}

const COPY = {
  ko: {
    title: '모델 검증',
    subtitle: '사전 예측과 최신 게시값을 구분해 오차를 확인합니다.',
    advance: '사전 예측 비교',
    reference: '최신 게시값 참고',
    comparisonMode: '비교 기준',
    metricMode: '오차 지표',
    gap: 'MAE 차이 (모델 − TEPCO)',
    loadError: '비교 데이터를 불러오지 못했습니다.',
    opsTitle: '최신 게시값 기준 오차 비교',
    backtestTitle: '모델 백테스트',
    maeHelp: 'MAE는 평균 오차 규모, WAPE는 전체 수요 대비 오차율, RMSE는 큰 오차 리스크를 봅니다. 낮을수록 실제 수요에 가깝습니다.',
    opsScopeNote: 'TEPCO는 과거 예측값을 수정할 수 있어 사전 예측의 공정한 성능 판정으로 사용하지 않습니다. 아래 범위는 모델 계열 기준이며 동일 버전만의 집계가 아닙니다.',
    backtestScopeNote: '학습용 데이터와 평가용 데이터를 나눠서 계산했습니다.',
    trainWindow: '학습 구간',
    testWindow: '평가 구간',
    period: '기간',
    samples: '비교 시간',
    modelMae: '모델 MAE',
    tepcoMae: 'TEPCO MAE',
    modelWins: '모델 우위 시간',
    tepcoWins: 'TEPCO 우위 시간',
    winRate: '우위 시간 비율',
    modelWape: '모델 WAPE',
    tepcoWape: 'TEPCO WAPE',
    rmseRisk: 'RMSE 리스크',
    maxErrorRisk: '최대 오차 리스크',
    advantageHours: 'TEPCO 대비 우위 시간',
    assessment: '게시값 기준 비교',
    modelScope: '집계 대상',
    smallerBetter: '낮을수록 좋습니다.',
    dailyTrend: '최근 일별 오차',
    recentDays: '일별 상세',
    date: '날짜',
    hours: '시간',
    winner: '게시값 비교',
    comment: '코멘트',
    commentModelBetter: '모델이 더 가까웠습니다.',
    commentTepcoBetter: 'TEPCO가 더 가까웠습니다.',
    commentClose: '두 예측이 비슷했습니다.',
    commentMixed: '평균 오차와 큰 오차 리스크가 엇갈립니다.',
    commentInsufficient: '아직 비교 시간이 부족합니다.',
    commentModelMiss: '모델 오차가 커진 날입니다.',
    partialPrefix: '부분 집계',
    model: '모델',
    tepco: 'TEPCO',
    mixed: '혼재',
    tie: '비슷함',
    baseline: '요일/시간 베이스라인',
    lightgbm: 'LightGBM',
    rmse: 'RMSE',
    mae: 'MAE',
    mape: 'MAPE',
    improvement: '개선율',
    unavailable: '검증 데이터가 아직 없습니다.',
    backtestUnavailable: '백테스트 산출물이 아직 없습니다. 다음 일일 ETL 이후 자동 생성됩니다.',
  },
  en: {
    title: 'Model Validation',
    subtitle: 'Separate advance forecasts from latest-published values when comparing errors.',
    advance: 'Advance comparison',
    reference: 'Latest-published reference',
    comparisonMode: 'Comparison basis',
    metricMode: 'Error metric',
    gap: 'MAE gap (model − TEPCO)',
    loadError: 'Could not load comparison data.',
    opsTitle: 'Latest-published error reference',
    backtestTitle: 'Model Backtest',
    maeHelp: 'MAE shows average MW error, WAPE shows error as a share of total load, and RMSE highlights large-error risk. Lower is better.',
    opsScopeNote: 'TEPCO may revise past forecasts, so this is not a fair advance-forecast assessment. The scope below uses model families, not a single model version.',
    backtestScopeNote: 'Training data and evaluation data are separated.',
    trainWindow: 'Training window',
    testWindow: 'Test window',
    period: 'Period',
    samples: 'Comparable hours',
    modelMae: 'Model MAE',
    tepcoMae: 'TEPCO MAE',
    modelWins: 'Model advantage hours',
    tepcoWins: 'TEPCO advantage hours',
    winRate: 'Advantage rate',
    modelWape: 'Model WAPE',
    tepcoWape: 'TEPCO WAPE',
    rmseRisk: 'RMSE risk',
    maxErrorRisk: 'Max error risk',
    advantageHours: 'Model advantage hours',
    assessment: 'Published-value comparison',
    modelScope: 'Scope',
    smallerBetter: 'Lower is better.',
    dailyTrend: 'Recent daily errors',
    recentDays: 'Daily details',
    date: 'Date',
    hours: 'Hours',
    winner: 'Published comparison',
    comment: 'Comment',
    commentModelBetter: 'The model was closer.',
    commentTepcoBetter: 'TEPCO was closer.',
    commentClose: 'Both forecasts were similar.',
    commentMixed: 'Average error and large-error risk are mixed.',
    commentInsufficient: 'Not enough comparable hours yet.',
    commentModelMiss: 'The model error widened that day.',
    partialPrefix: 'Partial coverage',
    model: 'Model',
    tepco: 'TEPCO',
    mixed: 'Mixed',
    tie: 'Close',
    baseline: 'Weekday/hour baseline',
    lightgbm: 'LightGBM',
    rmse: 'RMSE',
    mae: 'MAE',
    mape: 'MAPE',
    improvement: 'Improvement',
    unavailable: 'Validation data is not available yet.',
    backtestUnavailable: 'Backtest output is not available yet. It will be generated by the next daily ETL run.',
  },
  ja: {
    title: 'モデル検証',
    subtitle: '事前予測と最新公開値を区別して誤差を確認します。',
    advance: '事前予測比較',
    reference: '最新公開値の参考',
    comparisonMode: '比較基準',
    metricMode: '誤差指標',
    gap: 'MAE差 (モデル − TEPCO)',
    loadError: '比較データを取得できませんでした。',
    opsTitle: '最新公開値ベースの誤差比較',
    backtestTitle: 'モデルバックテスト',
    maeHelp: 'MAEは平均的なMW誤差、WAPEは総需要に対する誤差率、RMSEは大きな誤差リスクを示します。低いほど良好です。',
    opsScopeNote: 'TEPCOは過去予測を修正する場合があり、厳密な事前予測の性能判定には使いません。下記はモデル系統別の範囲で、単一バージョンの集計ではありません。',
    backtestScopeNote: '学習データと評価データを分けて計算しています。',
    trainWindow: '学習期間',
    testWindow: '評価期間',
    period: '期間',
    samples: '比較時間',
    modelMae: 'モデルMAE',
    tepcoMae: 'TEPCO MAE',
    modelWins: 'モデル優位時間',
    tepcoWins: 'TEPCO優位時間',
    winRate: '優位時間率',
    modelWape: 'モデル WAPE',
    tepcoWape: 'TEPCO WAPE',
    rmseRisk: 'RMSEリスク',
    maxErrorRisk: '最大誤差リスク',
    advantageHours: 'TEPCO比の優位時間',
    assessment: '公開値ベースの比較',
    modelScope: '集計対象',
    smallerBetter: '低いほど良好です。',
    dailyTrend: '直近日別誤差',
    recentDays: '日別詳細',
    date: '日付',
    hours: '時間',
    winner: '公開値比較',
    comment: 'コメント',
    commentModelBetter: 'モデルの方が近い予測でした。',
    commentTepcoBetter: 'TEPCOの方が近い予測でした。',
    commentClose: '両方の予測はほぼ同等でした。',
    commentMixed: '平均誤差と大きな誤差リスクの評価が分かれています。',
    commentInsufficient: '比較できる時間がまだ不足しています。',
    commentModelMiss: 'モデル誤差が大きくなった日です。',
    partialPrefix: '部分集計',
    model: 'モデル',
    tepco: 'TEPCO',
    mixed: '混在',
    tie: '同程度',
    baseline: '曜日/時間ベースライン',
    lightgbm: 'LightGBM',
    rmse: 'RMSE',
    mae: 'MAE',
    mape: 'MAPE',
    improvement: '改善率',
    unavailable: '検証データはまだありません。',
    backtestUnavailable: 'バックテスト出力はまだありません。次回の日次ETLで自動生成されます。',
  },
}

const DAILY_REPORT_COPY = {
  ko: {
    title: '전날 운영 리포트',
    subtitle: '확정 실측 기준으로 전날 예측 품질을 요약합니다.',
    modelMae: '모델 MAE',
    tepcoMae: 'TEPCO MAE',
    winner: '게시값 비교',
    modelWape: '모델 WAPE',
    tepcoWape: 'TEPCO WAPE',
    rmseRisk: 'RMSE 리스크',
    advantageHours: 'TEPCO 대비 우위 시간',
    peakError: '피크 오차',
    largestMiss: '최대 오차',
    insights: '주요 코멘트',
    noInsight: '특별히 큰 패턴 이탈은 감지되지 않았습니다.',
    severityInfo: '참고',
    severityWarning: '검토 필요',
    severityCritical: '우선 점검',
    model: '모델',
    tepco: 'TEPCO',
    mixed: '혼재',
    tie: '비슷함',
    close: '비슷함',
    hourSuffix: '시',
    insightText: {
      model_closer_overall: '전날 전체 기준으로 모델이 TEPCO보다 실제에 가까웠습니다.',
      tepco_closer_overall: '전날 전체 기준으로 TEPCO 예측이 더 가까웠습니다.',
      mixed_operational_assessment: '평균 오차와 큰 오차 리스크가 서로 다른 신호를 보였습니다.',
      morning_ramp_underestimated: '아침 수요 상승을 모델이 낮게 봤습니다.',
      morning_ramp_overestimated: '아침 수요 상승을 모델이 높게 봤습니다.',
      daytime_level_underestimated: '낮 시간대 수요 수준을 낮게 봤습니다.',
      afternoon_plateau_underestimated: '늦은 오후 수요가 예상보다 오래 유지됐습니다.',
      large_single_hour_miss: '특정 시간대에서 큰 오차가 발생했습니다.',
      sharp_model_drop_mismatch: '모델 예측선이 실제 수요보다 빠르게 내려갔습니다.',
      sharp_model_rise_mismatch: '모델 예측선이 실제 수요보다 빠르게 올라갔습니다.',
      peak_timing_miss: '피크 발생 시간이 실제와 어긋났습니다.',
      peak_level_underestimated: '실제 피크 수요가 모델 예상보다 높았습니다.',
      peak_level_overestimated: '실제 피크 수요가 모델 예상보다 낮았습니다.',
    } as Record<string, string>,
  },
  en: {
    title: 'Previous Day Operation Report',
    subtitle: 'Summarizes yesterday’s forecast quality after confirmed actuals arrive.',
    modelMae: 'Model MAE',
    tepcoMae: 'TEPCO MAE',
    winner: 'Published-value comparison',
    modelWape: 'Model WAPE',
    tepcoWape: 'TEPCO WAPE',
    rmseRisk: 'RMSE risk',
    advantageHours: 'Model advantage hours',
    peakError: 'Peak error',
    largestMiss: 'Largest miss',
    insights: 'Key comments',
    noInsight: 'No major recurring pattern was detected.',
    severityInfo: 'Info',
    severityWarning: 'Needs Review',
    severityCritical: 'Priority Review',
    model: 'Model',
    tepco: 'TEPCO',
    mixed: 'Mixed',
    tie: 'Close',
    close: 'Close',
    hourSuffix: ':00',
    insightText: {
      model_closer_overall: 'The model was closer than TEPCO overall.',
      tepco_closer_overall: 'TEPCO was closer overall.',
      mixed_operational_assessment: 'Average error and large-error risk pointed in different directions.',
      morning_ramp_underestimated: 'The model underestimated the morning demand ramp.',
      morning_ramp_overestimated: 'The model overestimated the morning demand ramp.',
      daytime_level_underestimated: 'The model underestimated daytime demand level.',
      afternoon_plateau_underestimated: 'Late afternoon demand stayed higher than expected.',
      large_single_hour_miss: 'One hour had a large model error.',
      sharp_model_drop_mismatch: 'The model line dropped faster than actual demand.',
      sharp_model_rise_mismatch: 'The model line rose faster than actual demand.',
      peak_timing_miss: 'The model peak occurred at a different hour than the actual peak.',
      peak_level_underestimated: 'The actual peak was higher than the model expected.',
      peak_level_overestimated: 'The actual peak was lower than the model expected.',
    } as Record<string, string>,
  },
  ja: {
    title: '前日運用レポート',
    subtitle: '確定実績を基準に、前日の予測品質を要約します。',
    modelMae: 'モデル MAE',
    tepcoMae: 'TEPCO MAE',
    winner: '公開値比較',
    modelWape: 'モデル WAPE',
    tepcoWape: 'TEPCO WAPE',
    rmseRisk: 'RMSEリスク',
    advantageHours: 'TEPCO比の優位時間',
    peakError: 'ピーク誤差',
    largestMiss: '最大誤差',
    insights: '主なコメント',
    noInsight: '大きな継続パターンのずれは検出されませんでした。',
    severityInfo: '情報',
    severityWarning: '要確認',
    severityCritical: '優先確認',
    model: 'モデル',
    tepco: 'TEPCO',
    mixed: '混在',
    tie: '同程度',
    close: '同程度',
    hourSuffix: '時',
    insightText: {
      model_closer_overall: '前日全体ではモデルの方がTEPCOより実績に近くなりました。',
      tepco_closer_overall: '前日全体ではTEPCO予測の方が近くなりました。',
      mixed_operational_assessment: '平均誤差と大きな誤差リスクの評価が分かれました。',
      morning_ramp_underestimated: '朝の需要上昇をモデルが低く見積もりました。',
      morning_ramp_overestimated: '朝の需要上昇をモデルが高く見積もりました。',
      daytime_level_underestimated: '日中の需要水準を低く見積もりました。',
      afternoon_plateau_underestimated: '夕方前の需要が想定より高く維持されました。',
      large_single_hour_miss: '特定時間帯で大きなモデル誤差が発生しました。',
      sharp_model_drop_mismatch: 'モデル予測線が実績需要より速く低下しました。',
      sharp_model_rise_mismatch: 'モデル予測線が実績需要より速く上昇しました。',
      peak_timing_miss: 'モデルのピーク時刻が実績ピークとずれました。',
      peak_level_underestimated: '実績ピークがモデル想定より高くなりました。',
      peak_level_overestimated: '実績ピークがモデル想定より低くなりました。',
    } as Record<string, string>,
  },
}

function fmtPct(value: number | null | undefined): string {
  if (value == null) return '-'
  return `${(value * 100).toFixed(1)}%`
}

function fmtMetricPct(value: number | null | undefined): string {
  if (value == null) return '-'
  return `${value > 0 ? '+' : ''}${value.toFixed(1)}%`
}

function fmtPowerMaybe(value: number | null | undefined, locale: Locale): string {
  return formatErrorPower(value, locale)
}

function fmtMape(value: number | null | undefined): string {
  return formatErrorPct(value)
}

function severityLabel(severity: DailyOperationReport['insights'][number]['severity'], labels: typeof DAILY_REPORT_COPY.ko): string {
  if (severity === 'critical') return labels.severityCritical
  if (severity === 'warning') return labels.severityWarning
  return labels.severityInfo
}

type AccuracyVerdict = NonNullable<ForecastAccuracyDaily['verdict']>

function verdictOf(row: ForecastAccuracyDaily): AccuracyVerdict {
  if (row.verdict) return row.verdict
  if (row.modelMaeMw == null || row.tepcoMaeMw == null) return 'insufficient'
  const gapMw = row.modelMaeMw - row.tepcoMaeMw
  if (Math.abs(gapMw) <= 50) return 'close'
  return gapMw < 0 ? 'model_better' : 'tepco_better'
}

function summaryVerdict(summary: ForecastAccuracyJSON['summary']): AccuracyVerdict {
  if (summary.verdict) return summary.verdict
  if (summary.modelMaeMw == null || summary.tepcoMaeMw == null) return 'insufficient'
  const gapMw = summary.modelMaeMw - summary.tepcoMaeMw
  if (Math.abs(gapMw) <= 50) return 'close'
  return gapMw < 0 ? 'model_better' : 'tepco_better'
}

function assessmentLabel(verdict: AccuracyVerdict | undefined, labels: typeof COPY.ko): string {
  if (verdict === 'model_better') return labels.model
  if (verdict === 'tepco_better') return labels.tepco
  if (verdict === 'mixed') return labels.mixed
  if (verdict === 'close') return labels.tie
  return '-'
}

function assessmentBadge(verdict: AccuracyVerdict | undefined): string {
  if (verdict === 'model_better') return 'ok'
  if (verdict === 'tepco_better') return 'warning'
  return 'info'
}

function advantageHoursValue(modelHours: number | undefined, totalHours: number | undefined, locale: Locale): string {
  const count = modelHours ?? 0
  const total = totalHours ?? 0
  if (locale === 'ko') return `${count}/${total}시간`
  if (locale === 'ja') return `${count}/${total}時間`
  return `${count}/${total}h`
}

function advantageHoursSub(
  modelHours: number | undefined,
  tepcoHours: number | undefined,
  equalHours: number | undefined,
  rate: number | null | undefined,
  labels: { model: string; tepco: string; tie: string },
): string {
  return `${labels.model} ${modelHours ?? 0} · ${labels.tepco} ${tepcoHours ?? 0} · ${labels.tie} ${equalHours ?? 0} · ${fmtPct(rate)}`
}

function commentFor(row: ForecastAccuracyDaily, labels: typeof COPY.ko): string {
  const verdict = verdictOf(row)
  const gapMw = row.maeGapMw ?? (
    row.modelMaeMw != null && row.tepcoMaeMw != null
      ? row.modelMaeMw - row.tepcoMaeMw
      : null
  )
  let comment = labels.commentInsufficient
  if (verdict === 'model_better') comment = labels.commentModelBetter
  if (verdict === 'tepco_better') comment = gapMw != null && gapMw >= 300
    ? labels.commentModelMiss
    : labels.commentTepcoBetter
  if (verdict === 'close') comment = labels.commentClose
  if (verdict === 'mixed') comment = labels.commentMixed
  return isPartialDay(row) ? `${labels.partialPrefix}: ${comment}` : comment
}

function periodSub(summaryDays: number, windowDays: number, locale: Locale): string {
  if (locale === 'ko') return `${summaryDays} / ${windowDays}일 집계`
  if (locale === 'ja') return `${summaryDays} / ${windowDays}日を集計`
  return `${summaryDays} / ${windowDays} days included`
}

function modelDisplayName(modelFamily: string | null | undefined, labels: typeof COPY.ko): string {
  if (!modelFamily) return '-'
  if (modelFamily.includes('lgbm')) return labels.lightgbm
  if (modelFamily.includes('baseline')) return labels.baseline
  return modelFamily
}

function StatCard({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="validation-stat">
      <div className="validation-stat-label">{label}</div>
      <div className="validation-stat-value">{value}</div>
      {sub && <div className="validation-stat-sub">{sub}</div>}
    </div>
  )
}

function BacktestMetricRow({ label, metric, locale }: {
  label: string
  metric: BacktestMetrics | null
  locale: Locale
}) {
  return (
    <tr>
      <td>{label}</td>
      <td>{fmtPowerMaybe(metric?.mae, locale)}</td>
      <td>{fmtPowerMaybe(metric?.rmse, locale)}</td>
      <td>{fmtMape(metric?.mape)}</td>
      <td>{metric?.n?.toLocaleString() ?? '-'}</td>
    </tr>
  )
}

function DailyTooltip({ active, payload, label, locale }: {
  active?: boolean
  payload?: Array<{ payload: { source: ForecastAccuracyDaily } }>
  label?: string
  locale: Locale
}) {
  if (!active || !payload?.length) return null
  const row = payload[0].payload.source
  const labels = COPY[locale]
  return (
    <div className="chart-tooltip">
      <div className="chart-tooltip-title">{row.date || label}</div>
      <div>{labels.modelMae}: {formatExactMw(row.modelMaeMw, locale)}</div>
      <div>{labels.tepcoMae}: {formatExactMw(row.tepcoMaeMw, locale)}</div>
      <div>{labels.gap}: {formatExactMw(errorGap(row.modelMaeMw, row.tepcoMaeMw), locale)}</div>
      <div>{labels.modelWape}: {fmtMape(row.modelWapePct)}</div>
      <div>{labels.tepcoWape}: {fmtMape(row.tepcoWapePct)}</div>
      <div>{labels.samples}: {row.hours}/24 {isPartialDay(row) ? `· ${labels.partialPrefix}` : ''}</div>
    </div>
  )
}

function reportAssessment(report: DailyOperationReport, labels: typeof DAILY_REPORT_COPY.ko): string {
  const verdict = report.summary.verdict
  if (verdict === 'model_better') return labels.model
  if (verdict === 'tepco_better') return labels.tepco
  if (verdict === 'mixed') return labels.mixed
  if (verdict === 'close') return labels.close
  return '-'
}

function reportAssessmentBadge(report: DailyOperationReport): string {
  const verdict = report.summary.verdict
  if (verdict === 'model_better') return 'ok'
  if (verdict === 'tepco_better') return 'warning'
  if (verdict === 'close') return 'info'
  if (verdict === 'mixed') return 'info'
  return 'info'
}

function formatHour(hour: number | null | undefined, locale: Locale, suffix: string): string {
  if (hour == null) return '-'
  if (locale === 'en') return `${hour.toString().padStart(2, '0')}${suffix}`
  return `${hour}${suffix}`
}

function insightText(code: string, labels: typeof DAILY_REPORT_COPY.ko): string {
  return labels.insightText[code] ?? code
}

function OperationReportCard({
  report,
  locale,
  fmtDate,
}: {
  report: DailyOperationReport
  locale: Locale
  fmtDate: (value: string) => string
}) {
  const labels = DAILY_REPORT_COPY[locale]
  const largestMiss = report.topMisses?.[0]
  const peakError = report.peak?.model.errorAtActualPeakMw
  return (
    <div className="card operation-report">
      <div className="card-title">{labels.title}</div>
      <p className="validation-note">{fmtDate(report.date)} · {labels.subtitle}</p>
      <div className="validation-stat-grid compact">
        <StatCard label={labels.modelMae} value={fmtPowerMaybe(report.summary.modelMaeMw, locale)} />
        <StatCard label={labels.tepcoMae} value={fmtPowerMaybe(report.summary.tepcoMaeMw, locale)} />
        <StatCard label={labels.modelWape} value={fmtMape(report.summary.modelWapePct)} />
        <StatCard label={labels.tepcoWape} value={fmtMape(report.summary.tepcoWapePct)} />
        <StatCard
          label={labels.rmseRisk}
          value={`${fmtPowerMaybe(report.summary.modelRmseMw, locale)} / ${fmtPowerMaybe(report.summary.tepcoRmseMw, locale)}`}
          sub={`${labels.model} / ${labels.tepco}`}
        />
        <div className="validation-stat">
          <div className="validation-stat-label">{labels.winner}</div>
          <div className="validation-stat-value">
            <span className={`badge ${reportAssessmentBadge(report)}`}>
              {reportAssessment(report, labels)}
            </span>
          </div>
          <div className="validation-stat-sub">
            {advantageHoursSub(
              report.summary.modelAdvantageHours ?? report.summary.modelWins,
              report.summary.tepcoAdvantageHours ?? report.summary.tepcoWins,
              report.summary.equalHours ?? report.summary.ties,
              report.summary.modelAdvantageRate,
              labels,
            )}
          </div>
        </div>
        <StatCard
          label={labels.peakError}
          value={fmtPowerMaybe(peakError, locale)}
          sub={formatHour(report.peak?.actual.hour, locale, labels.hourSuffix)}
        />
        <StatCard
          label={labels.largestMiss}
          value={fmtPowerMaybe(largestMiss?.modelAbsErrorMw, locale)}
          sub={formatHour(largestMiss?.hour, locale, labels.hourSuffix)}
        />
      </div>
      <div className="operation-insights">
        <div className="operation-insights-title">{labels.insights}</div>
        {report.insights.length === 0 ? (
          <div className="operation-insight muted">{labels.noInsight}</div>
        ) : (
          report.insights.map(item => (
            <div key={item.code} className="operation-insight">
              <span className={`badge ${item.severity}`}>{severityLabel(item.severity, labels)}</span>
              <span>{insightText(item.code, labels)}</span>
            </div>
          ))
        )}
      </div>
    </div>
  )
}

export function ValidationPanel({ baseUrl }: Props) {
  const { t, locale, fmtDate } = useT()
  const labels = COPY[locale]
  const [comparison, setComparison] = useState<'advance' | 'reference'>('advance')
  const [metric, setMetric] = useState<ErrorMetric>('mae')
  const accuracy = useFetch<ForecastAccuracyJSON>(`${baseUrl}metrics/forecast_accuracy.json`)
  const backtest = useFetch<ModelBacktestJSON>(`${baseUrl}metrics/model_backtest.json`)
  const dailyReport = useFetch<DailyOperationReportIndex>(`${baseUrl}reports/daily/index.json`)

  const loading = accuracy.loading
  const latestReport = dailyReport.data?.latest
  const summary = accuracy.data?.summary
  const scopedDaily = referenceDays(accuracy.data?.daily ?? [])
  const daily = scopedDaily.slice(-14)
  const recentDaily = scopedDaily.slice(-10).reverse()
  const firstDaily = scopedDaily[0]
  const lastDaily = scopedDaily[scopedDaily.length - 1]
  const chartValue = (row: ForecastAccuracyDaily, source: 'model' | 'tepco') => {
    const value = referenceMetricValue(row, source, metric)
    return value == null || metric === 'wape' ? value : powerDisplayValue(value, locale)
  }
  const chartRows = daily.map(row => ({
    date: row.date.slice(5),
    source: row,
    model: chartValue(row, 'model'),
    tepco: chartValue(row, 'tepco'),
  }))

  return (
    <div className="tab-content">
      <div className="date-header">
        <h2>{labels.title}</h2>
        <p>{labels.subtitle}</p>
      </div>

      <div className="validation-mode" role="group" aria-label={labels.comparisonMode}>
        {(['advance', 'reference'] as const).map(mode => (
          <button key={mode} type="button" aria-pressed={comparison === mode} onClick={() => setComparison(mode)}>{labels[mode]}</button>
        ))}
      </div>

      {comparison === 'advance' && <VintageComparison baseUrl={baseUrl} />}

      {comparison === 'reference' && loading && <div className="loading" role="status">{t.loading}</div>}

      {comparison === 'reference' && !loading && !accuracy.data && (
        <div className="empty-msg" role={accuracy.error ? 'alert' : 'status'}>{accuracy.error ? labels.loadError : labels.unavailable}</div>
      )}

      {comparison === 'reference' && !loading && accuracy.data && summary && (
        <>
          <section className="validation-section">
            <div className="card-title">{labels.opsTitle}</div>
            <p className="validation-note">{labels.maeHelp}</p>
            <p className="validation-note">{labels.opsScopeNote}</p>
            <div className="validation-stat-grid">
              <StatCard
                label={labels.modelScope}
                value={modelDisplayName(accuracy.data.modelScope?.summaryModelFamily, labels)}
              />
              <StatCard
                label={labels.period}
                value={`${firstDaily?.date ?? '-'} ~ ${lastDaily?.date ?? '-'}`}
                sub={periodSub(summary.dates, accuracy.data.windowDays, locale)}
              />
              <StatCard label={labels.samples} value={summary.hours.toLocaleString()} />
              <StatCard label={labels.modelMae} value={fmtPowerMaybe(summary.modelMaeMw, locale)} sub={formatExactMw(summary.modelMaeMw, locale)} />
              <StatCard label={labels.tepcoMae} value={fmtPowerMaybe(summary.tepcoMaeMw, locale)} sub={formatExactMw(summary.tepcoMaeMw, locale)} />
              <StatCard label={labels.modelWape} value={fmtMape(summary.modelWapePct)} sub={labels.smallerBetter} />
              <StatCard label={labels.tepcoWape} value={fmtMape(summary.tepcoWapePct)} sub={labels.smallerBetter} />
              <StatCard label={labels.gap} value={formatExactMw(errorGap(summary.modelMaeMw, summary.tepcoMaeMw), locale)} />
              <StatCard
                label={labels.rmseRisk}
                value={`${fmtPowerMaybe(summary.modelRmseMw, locale)} / ${fmtPowerMaybe(summary.tepcoRmseMw, locale)}`}
                sub={`${labels.model} / ${labels.tepco}`}
              />
              <StatCard
                label={labels.maxErrorRisk}
                value={`${fmtPowerMaybe(summary.modelMaxErrorMw, locale)} / ${fmtPowerMaybe(summary.tepcoMaxErrorMw, locale)}`}
                sub={`${labels.model} / ${labels.tepco}`}
              />
              <StatCard
                label={labels.advantageHours}
                value={advantageHoursValue(summary.modelAdvantageHours ?? summary.modelWins, summary.hours, locale)}
                sub={advantageHoursSub(
                  summary.modelAdvantageHours ?? summary.modelWins,
                  summary.tepcoAdvantageHours ?? summary.tepcoWins,
                  summary.equalHours ?? summary.ties,
                  summary.modelAdvantageRate ?? summary.modelWinRate,
                  labels,
                )}
              />
              <div className="validation-stat">
                <div className="validation-stat-label">{labels.assessment}</div>
                <div className="validation-stat-value">
                  <span className={`badge ${assessmentBadge(summaryVerdict(summary))}`}>
                    {assessmentLabel(summaryVerdict(summary), labels)}
                  </span>
                </div>
                <div className="validation-stat-sub">
                  {commentFor({
                    date: '',
                    hours: 24,
                    modelMaeMw: summary.modelMaeMw,
                    tepcoMaeMw: summary.tepcoMaeMw,
                    maeGapMw: summary.modelMaeMw != null && summary.tepcoMaeMw != null
                      ? summary.modelMaeMw - summary.tepcoMaeMw
                      : null,
                    verdict: summaryVerdict(summary),
                    modelWins: summary.modelWins,
                    tepcoWins: summary.tepcoWins,
                    ties: summary.ties,
                  }, labels)}
                </div>
              </div>
            </div>
          </section>

          {chartRows.length > 0 && (
            <section className="validation-section chart-container">
              <div className="validation-chart-heading">
                <div className="card-title">{labels.dailyTrend} · {metric.toUpperCase()}</div>
                <div className="validation-mode" role="group" aria-label={labels.metricMode}>
                  {(['mae', 'wape'] as const).map(value => <button key={value} type="button" aria-pressed={metric === value} onClick={() => setMetric(value)}>{value.toUpperCase()}</button>)}
                </div>
              </div>
              <p className="validation-note">{daily[0]?.date} ~ {daily[daily.length - 1]?.date} · {daily.length} {locale === 'en' ? 'days' : locale === 'ja' ? '日' : '일'}</p>
              {daily.some(isPartialDay) && <p className="validation-note">{labels.partialPrefix}: {daily.filter(isPartialDay).map(row => `${row.date} (${row.hours}/24h)`).join(', ')}</p>}
              <ResponsiveContainer width="100%" height={260}>
                <BarChart accessibilityLayer data={chartRows} margin={{ top: 24, right: 8, bottom: 0, left: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="date" tick={{ fontSize: 11 }} />
                  <YAxis
                    domain={[0, 'auto']}
                    tickFormatter={(v: number) => v.toLocaleString(locale, { maximumFractionDigits: metric === 'wape' || locale === 'en' ? 2 : 0 })}
                    tick={{ fontSize: 11 }}
                    width={52}
                    label={{ value: metric === 'wape' ? '%' : powerUnit(locale), position: 'top', offset: 8, style: { fontSize: 10, fill: '#64748b' } }}
                  />
                  <Tooltip content={<DailyTooltip locale={locale} />} />
                  <Legend wrapperStyle={{ fontSize: 12 }} />
                  <Bar dataKey="model" name={labels.model} fill="#2563eb" radius={[3, 3, 0, 0]} />
                  <Bar dataKey="tepco" name={labels.tepco} fill="#7c3aed" radius={[3, 3, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </section>
          )}

          {recentDaily.length > 0 && (
            <section className="validation-section">
              <div className="card-title">{labels.recentDays}</div>
              <p className="validation-note">{recentDaily[recentDaily.length - 1]?.date} ~ {recentDaily[0]?.date} · {labels.model} / TEPCO</p>
              <div className="validation-table-wrap" tabIndex={0} role="region" aria-label={labels.recentDays}>
                <table className="validation-table">
                  <thead>
                    <tr>
                      <th>{labels.date}</th>
                      <th>{labels.hours}</th>
                      <th>{labels.mae}</th>
                      <th>WAPE</th>
                      <th>{labels.rmse}</th>
                      <th>{labels.advantageHours}</th>
                      <th>{labels.winner}</th>
                      <th>{labels.comment}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {recentDaily.map(row => (
                      <tr key={row.date}>
                        <td>{fmtDate(row.date)}</td>
                        <td>{row.hours}/24 {isPartialDay(row) && <span className="badge info">{labels.partialPrefix}</span>}</td>
                        <td>{fmtPowerMaybe(row.modelMaeMw, locale)} / {fmtPowerMaybe(row.tepcoMaeMw, locale)}</td>
                        <td>{fmtMape(row.modelWapePct)} / {fmtMape(row.tepcoWapePct)}</td>
                        <td>{fmtPowerMaybe(row.modelRmseMw, locale)} / {fmtPowerMaybe(row.tepcoRmseMw, locale)}</td>
                        <td>
                          {advantageHoursValue(row.modelAdvantageHours ?? row.modelWins, row.hours, locale)}
                        </td>
                        <td>
                          <span className={`badge ${assessmentBadge(verdictOf(row))}`}>
                            {assessmentLabel(verdictOf(row), labels)}
                          </span>
                        </td>
                        <td className="validation-comment">{commentFor(row, labels)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>
          )}
        </>
      )}

      {comparison === 'reference' && !loading && latestReport && (
        <OperationReportCard report={latestReport} locale={locale} fmtDate={fmtDate} />
      )}

      {!backtest.loading && (
        <div className="card">
          <div className="card-title">{labels.backtestTitle}</div>
          {!backtest.data ? (
            <div className="empty-msg">{labels.backtestUnavailable}</div>
          ) : (
            <>
              <p className="validation-note">{labels.backtestScopeNote}</p>
              <div className="validation-stat-grid compact">
                <StatCard
                  label={labels.trainWindow}
                  value={`${backtest.data.trainPeriod.start} ~ ${backtest.data.trainPeriod.end}`}
                  sub={`${backtest.data.trainPeriod.rows.toLocaleString()} rows`}
                />
                <StatCard
                  label={labels.testWindow}
                  value={`${backtest.data.testPeriod.start} ~ ${backtest.data.testPeriod.end}`}
                  sub={`${backtest.data.testPeriod.days} days`}
                />
                <StatCard
                  label={`${labels.rmse} ${labels.improvement}`}
                  value={fmtMetricPct(backtest.data.improvementPct.rmse)}
                />
                <StatCard
                  label={`${labels.mae} ${labels.improvement}`}
                  value={fmtMetricPct(backtest.data.improvementPct.mae)}
                />
              </div>
              <div className="validation-table-wrap">
                <table className="validation-table">
                  <thead>
                    <tr>
                      <th>{labels.model}</th>
                      <th>{labels.mae}</th>
                      <th>{labels.rmse}</th>
                      <th>{labels.mape}</th>
                      <th>n</th>
                    </tr>
                  </thead>
                  <tbody>
                    <BacktestMetricRow label={labels.baseline} metric={backtest.data.baseline} locale={locale} />
                    <BacktestMetricRow label={labels.lightgbm} metric={backtest.data.lightgbm} locale={locale} />
                  </tbody>
                </table>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  )
}
