import {
  Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from 'recharts'
import { useFetch } from '../hooks/useFetch'
import { useT, type Locale } from '../i18n'
import type {
  BacktestMetrics,
  DailyOperationReport,
  DailyOperationReportIndex,
  ForecastAccuracyDaily,
  ForecastAccuracyJSON,
  ModelBacktestJSON,
} from '../types'
import { formatPower, formatPowerDisplayValue, powerDisplayValue, powerUnit } from '../units'

interface Props {
  baseUrl: string
}

const COPY = {
  ko: {
    title: '모델 검증',
    subtitle: '백테스트와 TEPCO 예측 대비 운영 성능을 함께 확인합니다.',
    opsTitle: 'TEPCO 예측 대비 운영 비교',
    backtestTitle: '모델 백테스트',
    maeHelp: 'MAE는 평균 절대 오차입니다. 실적과 예측의 차이를 평균낸 값이라 낮을수록 실제 수요에 더 가깝습니다.',
    opsScopeNote: '최근 같은 모델로 만든 예측만 모아 TEPCO와 비교합니다.',
    backtestScopeNote: '학습용 데이터와 평가용 데이터를 나눠서 계산했습니다.',
    trainWindow: '학습 구간',
    testWindow: '평가 구간',
    period: '기간',
    samples: '비교 시간',
    modelMae: '모델 MAE',
    tepcoMae: 'TEPCO MAE',
    modelWins: '모델 우세',
    tepcoWins: 'TEPCO 우세',
    winRate: '모델 승률',
    modelScope: '집계 대상',
    smallerBetter: 'MAE는 낮을수록 좋습니다.',
    dailyTrend: '최근 일별 MAE',
    recentDays: '최근 일별 판정',
    date: '날짜',
    hours: '시간',
    winner: '우세',
    comment: '코멘트',
    commentModelBetter: '모델이 더 가까웠습니다.',
    commentTepcoBetter: 'TEPCO가 더 가까웠습니다.',
    commentClose: '두 예측이 비슷했습니다.',
    commentInsufficient: '아직 비교 시간이 부족합니다.',
    commentModelMiss: '모델 오차가 커진 날입니다.',
    partialPrefix: '집계 중',
    model: '모델',
    tepco: 'TEPCO',
    baseline: '요일/시간 베이스라인',
    lightgbm: 'LightGBM',
    rmse: 'RMSE',
    mae: 'MAE',
    mape: 'MAPE',
    improvement: '개선율',
    unavailable: '검증 데이터가 아직 없습니다.',
    backtestUnavailable: '백테스트 산출물이 아직 없습니다. 다음 일일 ETL 이후 자동 생성됩니다.',
  },
  en: {
    title: 'Model Validation',
    subtitle: 'Backtest results and operational accuracy against TEPCO forecasts.',
    opsTitle: 'Operational Comparison vs TEPCO',
    backtestTitle: 'Model Backtest',
    maeHelp: 'MAE is mean absolute error: the average gap between actual demand and forecast. Lower means closer to actual load.',
    opsScopeNote: 'Compares TEPCO against recent forecasts made by the same model.',
    backtestScopeNote: 'Training data and evaluation data are separated.',
    trainWindow: 'Training window',
    testWindow: 'Test window',
    period: 'Period',
    samples: 'Comparable hours',
    modelMae: 'Model MAE',
    tepcoMae: 'TEPCO MAE',
    modelWins: 'Model wins',
    tepcoWins: 'TEPCO wins',
    winRate: 'Model win rate',
    modelScope: 'Scope',
    smallerBetter: 'Lower MAE is better.',
    dailyTrend: 'Recent Daily MAE',
    recentDays: 'Recent Daily Verdict',
    date: 'Date',
    hours: 'Hours',
    winner: 'Winner',
    comment: 'Comment',
    commentModelBetter: 'The model was closer.',
    commentTepcoBetter: 'TEPCO was closer.',
    commentClose: 'Both forecasts were similar.',
    commentInsufficient: 'Not enough comparable hours yet.',
    commentModelMiss: 'The model error widened that day.',
    partialPrefix: 'In progress',
    model: 'Model',
    tepco: 'TEPCO',
    baseline: 'Weekday/hour baseline',
    lightgbm: 'LightGBM',
    rmse: 'RMSE',
    mae: 'MAE',
    mape: 'MAPE',
    improvement: 'Improvement',
    unavailable: 'Validation data is not available yet.',
    backtestUnavailable: 'Backtest output is not available yet. It will be generated by the next daily ETL run.',
  },
  ja: {
    title: 'モデル検証',
    subtitle: 'バックテストとTEPCO予測に対する運用精度を確認します。',
    opsTitle: 'TEPCO予測との運用比較',
    backtestTitle: 'モデルバックテスト',
    maeHelp: 'MAEは平均絶対誤差です。実績と予測の差を平均した値で、低いほど実績需要に近いことを示します。',
    opsScopeNote: '同じモデルで作成した直近予測だけをTEPCOと比較します。',
    backtestScopeNote: '学習データと評価データを分けて計算しています。',
    trainWindow: '学習期間',
    testWindow: '評価期間',
    period: '期間',
    samples: '比較時間',
    modelMae: 'モデルMAE',
    tepcoMae: 'TEPCO MAE',
    modelWins: 'モデル優勢',
    tepcoWins: 'TEPCO優勢',
    winRate: 'モデル勝率',
    modelScope: '集計対象',
    smallerBetter: 'MAEは低いほど良好です。',
    dailyTrend: '直近日別MAE',
    recentDays: '直近日別判定',
    date: '日付',
    hours: '時間',
    winner: '優勢',
    comment: 'コメント',
    commentModelBetter: 'モデルの方が近い予測でした。',
    commentTepcoBetter: 'TEPCOの方が近い予測でした。',
    commentClose: '両方の予測はほぼ同等でした。',
    commentInsufficient: '比較できる時間がまだ不足しています。',
    commentModelMiss: 'モデル誤差が大きくなった日です。',
    partialPrefix: '集計中',
    model: 'モデル',
    tepco: 'TEPCO',
    baseline: '曜日/時間ベースライン',
    lightgbm: 'LightGBM',
    rmse: 'RMSE',
    mae: 'MAE',
    mape: 'MAPE',
    improvement: '改善率',
    unavailable: '検証データはまだありません。',
    backtestUnavailable: 'バックテスト出力はまだありません。次回の日次ETLで自動生成されます。',
  },
}

const DAILY_REPORT_COPY = {
  ko: {
    title: '전날 운영 리포트',
    subtitle: '확정 실측 기준으로 전날 예측 품질을 요약합니다.',
    modelMae: '모델 MAE',
    tepcoMae: 'TEPCO MAE',
    winner: '우세',
    peakError: '피크 오차',
    largestMiss: '최대 오차',
    insights: '주요 코멘트',
    noInsight: '특별히 큰 패턴 이탈은 감지되지 않았습니다.',
    model: '모델',
    tepco: 'TEPCO',
    close: '비슷함',
    hourSuffix: '시',
    insightText: {
      model_closer_overall: '전날 전체 기준으로 모델이 TEPCO보다 실제에 가까웠습니다.',
      tepco_closer_overall: '전날 전체 기준으로 TEPCO 예측이 더 가까웠습니다.',
      morning_ramp_underestimated: '아침 수요 상승을 모델이 낮게 봤습니다.',
      morning_ramp_overestimated: '아침 수요 상승을 모델이 높게 봤습니다.',
      daytime_level_underestimated: '낮 시간대 수요 수준을 낮게 봤습니다.',
      afternoon_plateau_underestimated: '늦은 오후 수요가 예상보다 오래 유지됐습니다.',
      large_single_hour_miss: '특정 시간대에서 큰 오차가 발생했습니다.',
      peak_timing_miss: '피크 발생 시간이 실제와 어긋났습니다.',
      peak_level_underestimated: '실제 피크 수요가 모델 예상보다 높았습니다.',
      peak_level_overestimated: '실제 피크 수요가 모델 예상보다 낮았습니다.',
    } as Record<string, string>,
  },
  en: {
    title: 'Previous Day Operation Report',
    subtitle: 'Summarizes yesterday’s forecast quality after confirmed actuals arrive.',
    modelMae: 'Model MAE',
    tepcoMae: 'TEPCO MAE',
    winner: 'Winner',
    peakError: 'Peak error',
    largestMiss: 'Largest miss',
    insights: 'Key comments',
    noInsight: 'No major recurring pattern was detected.',
    model: 'Model',
    tepco: 'TEPCO',
    close: 'Close',
    hourSuffix: ':00',
    insightText: {
      model_closer_overall: 'The model was closer than TEPCO overall.',
      tepco_closer_overall: 'TEPCO was closer overall.',
      morning_ramp_underestimated: 'The model underestimated the morning demand ramp.',
      morning_ramp_overestimated: 'The model overestimated the morning demand ramp.',
      daytime_level_underestimated: 'The model underestimated daytime demand level.',
      afternoon_plateau_underestimated: 'Late afternoon demand stayed higher than expected.',
      large_single_hour_miss: 'One hour had a large model error.',
      peak_timing_miss: 'The model peak occurred at a different hour than the actual peak.',
      peak_level_underestimated: 'The actual peak was higher than the model expected.',
      peak_level_overestimated: 'The actual peak was lower than the model expected.',
    } as Record<string, string>,
  },
  ja: {
    title: '前日運用レポート',
    subtitle: '確定実績を基準に、前日の予測品質を要約します。',
    modelMae: 'モデル MAE',
    tepcoMae: 'TEPCO MAE',
    winner: '優勢',
    peakError: 'ピーク誤差',
    largestMiss: '最大誤差',
    insights: '主なコメント',
    noInsight: '大きな継続パターンのずれは検出されませんでした。',
    model: 'モデル',
    tepco: 'TEPCO',
    close: '同程度',
    hourSuffix: '時',
    insightText: {
      model_closer_overall: '前日全体ではモデルの方がTEPCOより実績に近くなりました。',
      tepco_closer_overall: '前日全体ではTEPCO予測の方が近くなりました。',
      morning_ramp_underestimated: '朝の需要上昇をモデルが低く見積もりました。',
      morning_ramp_overestimated: '朝の需要上昇をモデルが高く見積もりました。',
      daytime_level_underestimated: '日中の需要水準を低く見積もりました。',
      afternoon_plateau_underestimated: '夕方前の需要が想定より高く維持されました。',
      large_single_hour_miss: '特定時間帯で大きなモデル誤差が発生しました。',
      peak_timing_miss: 'モデルのピーク時刻が実績ピークとずれました。',
      peak_level_underestimated: '実績ピークがモデル想定より高くなりました。',
      peak_level_overestimated: '実績ピークがモデル想定より低くなりました。',
    } as Record<string, string>,
  },
}

function fmtPct(value: number | null | undefined): string {
  if (value == null) return '-'
  return `${(value * 100).toFixed(1)}%`
}

function fmtMetricPct(value: number | null | undefined): string {
  if (value == null) return '-'
  return `${value > 0 ? '+' : ''}${value.toFixed(1)}%`
}

function fmtPowerMaybe(value: number | null | undefined, locale: Locale): string {
  if (value == null) return '-'
  return formatPower(value, locale)
}

function fmtMape(value: number | null | undefined): string {
  if (value == null) return '-'
  return `${value.toFixed(2)}%`
}

function winnerOf(row: ForecastAccuracyDaily, labels: typeof COPY.ko): string {
  if (row.modelMaeMw == null || row.tepcoMaeMw == null) return '-'
  if (row.modelMaeMw < row.tepcoMaeMw) return labels.model
  if (row.tepcoMaeMw < row.modelMaeMw) return labels.tepco
  return 'Tie'
}

function verdictOf(row: ForecastAccuracyDaily): ForecastAccuracyDaily['verdict'] {
  if (row.verdict) return row.verdict
  if (row.modelMaeMw == null || row.tepcoMaeMw == null) return 'insufficient'
  const gapMw = row.modelMaeMw - row.tepcoMaeMw
  if (Math.abs(gapMw) <= 50) return 'close'
  return gapMw < 0 ? 'model_better' : 'tepco_better'
}

function commentFor(row: ForecastAccuracyDaily, labels: typeof COPY.ko): string {
  const verdict = verdictOf(row)
  const gapMw = row.maeGapMw ?? (
    row.modelMaeMw != null && row.tepcoMaeMw != null
      ? row.modelMaeMw - row.tepcoMaeMw
      : null
  )
  let comment = labels.commentInsufficient
  if (verdict === 'model_better') comment = labels.commentModelBetter
  if (verdict === 'tepco_better') comment = gapMw != null && gapMw >= 300
    ? labels.commentModelMiss
    : labels.commentTepcoBetter
  if (verdict === 'close') comment = labels.commentClose
  return row.hours < 24 ? `${labels.partialPrefix}: ${comment}` : comment
}

function periodSub(summaryDays: number, windowDays: number, locale: Locale): string {
  if (locale === 'ko') return `${summaryDays} / ${windowDays}일 집계`
  if (locale === 'ja') return `${summaryDays} / ${windowDays}日を集計`
  return `${summaryDays} / ${windowDays} days included`
}

function modelDisplayName(modelFamily: string | null | undefined, labels: typeof COPY.ko): string {
  if (!modelFamily) return '-'
  if (modelFamily.includes('lgbm')) return labels.lightgbm
  if (modelFamily.includes('baseline')) return labels.baseline
  return modelFamily
}

function StatCard({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="validation-stat">
      <div className="validation-stat-label">{label}</div>
      <div className="validation-stat-value">{value}</div>
      {sub && <div className="validation-stat-sub">{sub}</div>}
    </div>
  )
}

function BacktestMetricRow({ label, metric, locale }: {
  label: string
  metric: BacktestMetrics | null
  locale: Locale
}) {
  return (
    <tr>
      <td>{label}</td>
      <td>{fmtPowerMaybe(metric?.mae, locale)}</td>
      <td>{fmtPowerMaybe(metric?.rmse, locale)}</td>
      <td>{fmtMape(metric?.mape)}</td>
      <td>{metric?.n?.toLocaleString() ?? '-'}</td>
    </tr>
  )
}

function DailyTooltip({ active, payload, label, locale }: {
  active?: boolean
  payload?: Array<{ dataKey: string; value: number; color?: string; name?: string }>
  label?: string
  locale: Locale
}) {
  if (!active || !payload?.length) return null
  return (
    <div className="chart-tooltip">
      <div className="chart-tooltip-title">{label}</div>
      {payload.map(item => (
        <div key={item.dataKey} style={{ color: item.color }}>
          {item.name}: {formatPowerDisplayValue(item.value, locale)} {powerUnit(locale)}
        </div>
      ))}
    </div>
  )
}

function reportWinner(report: DailyOperationReport, labels: typeof DAILY_REPORT_COPY.ko): string {
  const verdict = report.summary.verdict
  if (verdict === 'model_better') return labels.model
  if (verdict === 'tepco_better') return labels.tepco
  if (verdict === 'close') return labels.close
  return '-'
}

function reportWinnerBadge(report: DailyOperationReport): string {
  const verdict = report.summary.verdict
  if (verdict === 'model_better') return 'ok'
  if (verdict === 'tepco_better') return 'warning'
  if (verdict === 'close') return 'info'
  return 'info'
}

function formatHour(hour: number | null | undefined, locale: Locale, suffix: string): string {
  if (hour == null) return '-'
  if (locale === 'en') return `${hour.toString().padStart(2, '0')}${suffix}`
  return `${hour}${suffix}`
}

function insightText(code: string, labels: typeof DAILY_REPORT_COPY.ko): string {
  return labels.insightText[code] ?? code
}

function OperationReportCard({
  report,
  locale,
  fmtDate,
}: {
  report: DailyOperationReport
  locale: Locale
  fmtDate: (value: string) => string
}) {
  const labels = DAILY_REPORT_COPY[locale]
  const largestMiss = report.topMisses?.[0]
  const peakError = report.peak?.model.errorAtActualPeakMw
  return (
    <div className="card operation-report">
      <div className="card-title">{labels.title}</div>
      <p className="validation-note">{fmtDate(report.date)} · {labels.subtitle}</p>
      <div className="validation-stat-grid compact">
        <StatCard label={labels.modelMae} value={fmtPowerMaybe(report.summary.modelMaeMw, locale)} />
        <StatCard label={labels.tepcoMae} value={fmtPowerMaybe(report.summary.tepcoMaeMw, locale)} />
        <div className="validation-stat">
          <div className="validation-stat-label">{labels.winner}</div>
          <div className="validation-stat-value">
            <span className={`badge ${reportWinnerBadge(report)}`}>
              {reportWinner(report, labels)}
            </span>
          </div>
          <div className="validation-stat-sub">
            {report.summary.comparableHours}h · {report.summary.modelWins ?? 0}:{report.summary.tepcoWins ?? 0}
          </div>
        </div>
        <StatCard
          label={labels.peakError}
          value={fmtPowerMaybe(peakError, locale)}
          sub={formatHour(report.peak?.actual.hour, locale, labels.hourSuffix)}
        />
        <StatCard
          label={labels.largestMiss}
          value={fmtPowerMaybe(largestMiss?.modelAbsErrorMw, locale)}
          sub={formatHour(largestMiss?.hour, locale, labels.hourSuffix)}
        />
      </div>
      <div className="operation-insights">
        <div className="operation-insights-title">{labels.insights}</div>
        {report.insights.length === 0 ? (
          <div className="operation-insight muted">{labels.noInsight}</div>
        ) : (
          report.insights.map(item => (
            <div key={item.code} className="operation-insight">
              <span className={`badge ${item.severity}`}>{item.severity}</span>
              <span>{insightText(item.code, labels)}</span>
            </div>
          ))
        )}
      </div>
    </div>
  )
}

export function ValidationPanel({ baseUrl }: Props) {
  const { t, locale, fmtDate } = useT()
  const labels = COPY[locale]
  const accuracy = useFetch<ForecastAccuracyJSON>(`${baseUrl}metrics/forecast_accuracy.json`)
  const backtest = useFetch<ModelBacktestJSON>(`${baseUrl}metrics/model_backtest.json`)
  const dailyReport = useFetch<DailyOperationReportIndex>(`${baseUrl}reports/daily/index.json`)

  const loading = accuracy.loading || backtest.loading
  const latestReport = dailyReport.data?.latest
  const summary = accuracy.data?.summary
  const scopedDaily = accuracy.data?.daily.filter(row => row.includedInSummary ?? true) ?? []
  const daily = scopedDaily.slice(-14)
  const recentDaily = scopedDaily.slice(-10).reverse()
  const firstDaily = scopedDaily[0]
  const lastDaily = scopedDaily[scopedDaily.length - 1]
  const chartRows = daily.map(row => ({
    date: row.date.slice(5),
    [labels.model]: row.modelMaeMw != null ? powerDisplayValue(row.modelMaeMw, locale) : null,
    [labels.tepco]: row.tepcoMaeMw != null ? powerDisplayValue(row.tepcoMaeMw, locale) : null,
  }))

  return (
    <div className="tab-content">
      <div className="date-header">
        <h2>{labels.title}</h2>
        <p>{labels.subtitle}</p>
      </div>

      {loading && <div className="loading">{t.loading}</div>}

      {!loading && !accuracy.data && (
        <div className="card empty-msg">{labels.unavailable}</div>
      )}

      {!loading && latestReport && (
        <OperationReportCard report={latestReport} locale={locale} fmtDate={fmtDate} />
      )}

      {!loading && accuracy.data && summary && (
        <>
          <div className="card">
            <div className="card-title">{labels.opsTitle}</div>
            <p className="validation-note">{labels.maeHelp}</p>
            <p className="validation-note">{labels.opsScopeNote}</p>
            <div className="validation-stat-grid">
              <StatCard
                label={labels.modelScope}
                value={modelDisplayName(accuracy.data.modelScope?.summaryModelFamily, labels)}
              />
              <StatCard
                label={labels.period}
                value={`${firstDaily?.date ?? '-'} ~ ${lastDaily?.date ?? '-'}`}
                sub={periodSub(summary.dates, accuracy.data.windowDays, locale)}
              />
              <StatCard label={labels.samples} value={summary.hours.toLocaleString()} />
              <StatCard label={labels.modelMae} value={fmtPowerMaybe(summary.modelMaeMw, locale)} sub={labels.smallerBetter} />
              <StatCard label={labels.tepcoMae} value={fmtPowerMaybe(summary.tepcoMaeMw, locale)} sub={labels.smallerBetter} />
              <StatCard label={labels.modelWins} value={summary.modelWins.toLocaleString()} />
              <StatCard label={labels.tepcoWins} value={summary.tepcoWins.toLocaleString()} />
              <StatCard label={labels.winRate} value={fmtPct(summary.modelWinRate)} />
            </div>
          </div>

          {chartRows.length > 0 && (
            <div className="card chart-container">
              <div className="card-title">{labels.dailyTrend}</div>
              <ResponsiveContainer width="100%" height={260}>
                <BarChart data={chartRows} margin={{ top: 4, right: 8, bottom: 0, left: 42 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="date" tick={{ fontSize: 11 }} />
                  <YAxis
                    tickFormatter={(v: number) => formatPowerDisplayValue(v, locale)}
                    tick={{ fontSize: 11 }}
                    width={52}
                    label={{ value: powerUnit(locale), angle: -90, position: 'insideLeft', offset: 12, style: { fontSize: 10, fill: '#94a3b8' } }}
                  />
                  <Tooltip content={<DailyTooltip locale={locale} />} />
                  <Legend wrapperStyle={{ fontSize: 12 }} />
                  <Bar dataKey={labels.model} name={labels.model} fill="#2563eb" radius={[3, 3, 0, 0]} />
                  <Bar dataKey={labels.tepco} name={labels.tepco} fill="#7c3aed" radius={[3, 3, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          )}

          {recentDaily.length > 0 && (
            <div className="card">
              <div className="card-title">{labels.recentDays}</div>
              <div className="validation-table-wrap">
                <table className="validation-table">
                  <thead>
                    <tr>
                      <th>{labels.date}</th>
                      <th>{labels.hours}</th>
                      <th>{labels.modelMae}</th>
                      <th>{labels.tepcoMae}</th>
                      <th>{labels.winner}</th>
                      <th>{labels.comment}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {recentDaily.map(row => (
                      <tr key={row.date}>
                        <td>{fmtDate(row.date)}</td>
                        <td>{row.hours}</td>
                        <td>{fmtPowerMaybe(row.modelMaeMw, locale)}</td>
                        <td>{fmtPowerMaybe(row.tepcoMaeMw, locale)}</td>
                        <td>
                          <span className={`badge ${winnerOf(row, labels) === labels.model ? 'ok' : 'info'}`}>
                            {winnerOf(row, labels)}
                          </span>
                        </td>
                        <td className="validation-comment">{commentFor(row, labels)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}

      {!loading && (
        <div className="card">
          <div className="card-title">{labels.backtestTitle}</div>
          {!backtest.data ? (
            <div className="empty-msg">{labels.backtestUnavailable}</div>
          ) : (
            <>
              <p className="validation-note">{labels.backtestScopeNote}</p>
              <div className="validation-stat-grid compact">
                <StatCard
                  label={labels.trainWindow}
                  value={`${backtest.data.trainPeriod.start} ~ ${backtest.data.trainPeriod.end}`}
                  sub={`${backtest.data.trainPeriod.rows.toLocaleString()} rows`}
                />
                <StatCard
                  label={labels.testWindow}
                  value={`${backtest.data.testPeriod.start} ~ ${backtest.data.testPeriod.end}`}
                  sub={`${backtest.data.testPeriod.days} days`}
                />
                <StatCard
                  label={`${labels.rmse} ${labels.improvement}`}
                  value={fmtMetricPct(backtest.data.improvementPct.rmse)}
                />
                <StatCard
                  label={`${labels.mae} ${labels.improvement}`}
                  value={fmtMetricPct(backtest.data.improvementPct.mae)}
                />
              </div>
              <div className="validation-table-wrap">
                <table className="validation-table">
                  <thead>
                    <tr>
                      <th>{labels.model}</th>
                      <th>{labels.mae}</th>
                      <th>{labels.rmse}</th>
                      <th>{labels.mape}</th>
                      <th>n</th>
                    </tr>
                  </thead>
                  <tbody>
                    <BacktestMetricRow label={labels.baseline} metric={backtest.data.baseline} locale={locale} />
                    <BacktestMetricRow label={labels.lightgbm} metric={backtest.data.lightgbm} locale={locale} />
                  </tbody>
                </table>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  )
}
